import "server-only";

import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { reportOperationalWarning } from "@/lib/ops-monitoring";

type CleanupRpcError={code?:string;message?:string}|null;
type CleanupRpcResult<T>={data:T|null;error:CleanupRpcError};
type CleanupAdmin=ReturnType<typeof createSupabaseAdminClient>;

const UUID_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const FILE_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.(jpg|png|webp)$/i;

const cleanupRpc=<T>(
 admin:CleanupAdmin,
 name:string,
 args:Record<string,unknown>
)=>(
 admin.rpc as unknown as (
  fn:string,
  values:Record<string,unknown>
 )=>Promise<CleanupRpcResult<T>>
)(name,args);

const cleanupSchemaMissing=(error:CleanupRpcError)=>
 Boolean(error&&(error.code==="PGRST202"||error.code==="42883"));

function validExactUploadPath(uploaderId:string,caseId:string,storagePath:string){
 if(!UUID_PATTERN.test(uploaderId)||!UUID_PATTERN.test(caseId))return false;
 const segments=storagePath.split("/");
 if(segments.length!==3)return false;
 return (
  segments[0].toLowerCase()===caseId.toLowerCase()&&
  segments[1].toLowerCase()===uploaderId.toLowerCase()&&
  FILE_PATTERN.test(segments[2])
 );
}

export async function processCaseEvidenceCleanup(limit=50,storagePath?:string){
 const admin=createSupabaseAdminClient();
 const {data,error}=await cleanupRpc<Array<{storage_path:string}>>(
  admin,
  "get_case_evidence_cleanup_queue",
  {
   p_limit:Math.max(1,Math.min(limit,100)),
   p_storage_path:storagePath
  }
 );

 if(error){
  if(cleanupSchemaMissing(error)){
   return {checked:0,completed:0,failed:0,skipped:true};
  }
  throw error;
 }

 let completed=0;
 let failed=0;
 for(const row of data??[]){
  try{
   const {error:storageError}=await admin.storage.from("case-evidence").remove([row.storage_path]);
   if(storageError)throw storageError;

   const {data:ack,error:ackError}=await cleanupRpc<boolean>(
    admin,
    "complete_case_evidence_cleanup",
    {p_storage_path:row.storage_path}
   );
   if(ackError||!ack)throw ackError??new Error("Case evidence cleanup acknowledgment failed.");
   completed+=1;
  }catch{
   failed+=1;
   await cleanupRpc<null>(
    admin,
    "fail_case_evidence_cleanup",
    {p_storage_path:row.storage_path}
   ).catch(()=>{});
  }
 }

 if(failed>0){
  reportOperationalWarning({
   component:"commerce_maintenance",
   event:"case_evidence_cleanup_pending",
   message:"Case evidence metadata attachment failed; Storage cleanup remains queued for retry.",
   context:{count:failed}
  });
 }

 return {checked:data?.length??0,completed,failed,skipped:false};
}

export async function attemptCaseEvidenceCleanup(storagePath:string){
 try{
  const result=await processCaseEvidenceCleanup(1,storagePath);
  return !result.skipped&&result.failed===0;
 }catch{
  reportOperationalWarning({
   component:"commerce_maintenance",
   event:"case_evidence_cleanup_unavailable",
   message:"Case evidence cleanup worker is temporarily unavailable."
  });
  return false;
 }
}

// Call only for the exact path generated by the server during the current
// authenticated upload attempt.
export async function cleanupFailedCaseEvidenceUpload(
 uploaderId:string,
 caseId:string,
 storagePath:string
){
 if(!validExactUploadPath(uploaderId,caseId,storagePath))return false;

 const admin=createSupabaseAdminClient();
 const {data,error}=await cleanupRpc<boolean>(
  admin,
  "queue_orphan_case_evidence_cleanup",
  {
   p_case_id:caseId,
   p_uploader_id:uploaderId,
   p_storage_path:storagePath
  }
 );

 if(!error){
  // False means an attached evidence row now exists; never remove its bytes.
  if(data===false)return true;
  if(data===true)return await attemptCaseEvidenceCleanup(storagePath);
  reportOperationalWarning({
   component:"commerce_maintenance",
   event:"case_evidence_cleanup_queue_uncertain",
   message:"Case evidence cleanup queue returned no authoritative result; Storage removal was deferred."
  });
  return false;
 }

 // Only a positively identified pre-migration missing-RPC response is allowed
 // to use the legacy exact-path removal. Any other queue error is uncertain:
 // registration may have committed even if its response was lost.
 if(!cleanupSchemaMissing(error)){
  reportOperationalWarning({
   component:"commerce_maintenance",
   event:"case_evidence_cleanup_queue_failed",
   message:"Durable case evidence cleanup could not be confirmed; Storage removal was deferred."
  });
  return false;
 }

 const {error:removeError}=await admin.storage.from("case-evidence").remove([storagePath]);
 if(removeError){
  reportOperationalWarning({
   component:"commerce_maintenance",
   event:"case_evidence_cleanup_fallback_failed",
   message:"Case evidence attachment failed and exact-path Storage cleanup could not be confirmed."
  });
  return false;
 }
 return true;
}
