import "server-only";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { reportOperationalWarning } from "@/lib/ops-monitoring";

export async function requirePartImageCleanupReady(){
 const {error}=await createSupabaseAdminClient().rpc("get_part_image_cleanup_queue",{p_limit:1,p_storage_path:""});
 if(error)throw new Error("Photo editing is temporarily unavailable. Please try again shortly.");
}

// This module never accepts deletion authority from a caller's path alone.
// Every Storage removal must be backed by the private durable outbox RPC.
export async function processPartImageCleanup(limit=50,storagePath?:string){
 const admin=createSupabaseAdminClient();
 const {data,error}=await admin.rpc("get_part_image_cleanup_queue",{
  p_limit:Math.max(1,Math.min(limit,100)),p_storage_path:storagePath
 });
 if(error)throw error;
 let completed=0;
 let failed=0;
 for(const row of data??[]){
  try{
   const {error:storageError}=await admin.storage.from("part-images").remove([row.storage_path]);
   if(storageError)throw storageError;
   const {data:ack,error:ackError}=await admin.rpc("complete_part_image_cleanup",{p_storage_path:row.storage_path});
   if(ackError||!ack)throw ackError??new Error("Image cleanup acknowledgment failed.");
   completed+=1;
  }catch{
   failed+=1;
   // Keep errors bounded and free of paths/provider response PII.
   await Promise.resolve(admin.rpc("fail_part_image_cleanup",{p_storage_path:row.storage_path})).catch(()=>{});
  }
 }
 if(failed>0)reportOperationalWarning({component:"commerce_maintenance",event:"part_image_cleanup_pending",message:"Photo metadata was removed; Storage cleanup remains queued for retry.",context:{count:failed}});
 return {checked:data?.length??0,completed,failed};
}

export async function attemptPartImageCleanup(storagePath:string){
 try{
  const result=await processPartImageCleanup(1,storagePath);
  return result.failed===0;
 }catch{
  reportOperationalWarning({component:"commerce_maintenance",event:"part_image_cleanup_unavailable",message:"Photo cleanup authorization is unavailable; Storage removal was deferred."});
  return false;
 }
}

// Only call with the path generated by the server for this upload attempt.
export async function cleanupFailedPartImageUpload(ownerId:string,partId:string,storagePath:string){
 try{
  const admin=createSupabaseAdminClient();
  const {data,error}=await admin.rpc("queue_orphan_part_image_cleanup",{
   p_owner_id:ownerId,p_part_id:partId,p_storage_path:storagePath
  });
  if(error||!data)return false;
  return await attemptPartImageCleanup(storagePath);
 }catch{return false;}
}
