"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/env";
import type { ActionState,UserRole } from "@/lib/types";

const safeReturnTo=(value:FormDataEntryValue|null)=>{const target=typeof value==="string"?value:"/account";return target.startsWith("/")&&!target.startsWith("//")?target:"/account";};
export async function signIn(_previous:ActionState,formData:FormData):Promise<ActionState>{if(!isSupabaseConfigured())return {status:"error",message:"Supabase is not configured."};const email=String(formData.get("email")??"").trim();const password=String(formData.get("password")??"");if(!email||!password)return {status:"error",message:"Enter your email and password."};const supabase=await createSupabaseServerClient();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return {status:"error",message:error.message};revalidatePath("/","layout");redirect(safeReturnTo(formData.get("returnTo")));}
export async function signUp(_previous:ActionState,formData:FormData):Promise<ActionState>{if(!isSupabaseConfigured())return {status:"error",message:"Supabase is not configured."};const email=String(formData.get("email")??"").trim();const password=String(formData.get("password")??"");const displayName=String(formData.get("displayName")??"").trim();const requestedRole=String(formData.get("role")??"buyer");const role:UserRole=requestedRole==="seller"?"seller":"buyer";if(displayName.length<2)return {status:"error",message:"Enter your name or business contact name."};if(!email.includes("@"))return {status:"error",message:"Enter a valid email address."};if(password.length<8)return {status:"error",message:"Use at least 8 characters for your password."};const supabase=await createSupabaseServerClient();const siteUrl=(process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000").replace(/\/$/,"");const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${siteUrl}/auth/callback`,data:{display_name:displayName,role}}});if(error)return {status:"error",message:error.message};if(data.session){revalidatePath("/","layout");redirect(role==="seller"?"/dashboard":"/account");}return {status:"success",message:"Check your email to confirm your account, then sign in."};}
export async function signOut(){if(isSupabaseConfigured()){const supabase=await createSupabaseServerClient();await supabase.auth.signOut();}revalidatePath("/","layout");redirect("/");}
