"use client";
import { useMemo,useState } from "react";
import { ArrowRight,BadgeCheck,ChevronDown,Search,ShieldCheck,SlidersHorizontal,Sparkles,Truck } from "lucide-react";
import type { Listing } from "@/lib/types";
import { Header } from "./header";
import { ProductCard } from "./product-card";

const categories=["All parts","Complete Gearboxes","Mechatronic Units","Clutch Assemblies","Valve Bodies","Repair Kits","Oil Pumps"];
export function MarketplaceHome({initialListings}:{initialListings:Listing[]}){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All parts"); const [saved,setSaved]=useState<string[]>([]); const [vehicle,setVehicle]=useState("Volkswagen Golf · 2017 · 2.0 TDI");
 const filtered=useMemo(()=>initialListings.filter((p)=>(category==="All parts"||p.category===category)&&`${p.title} ${p.code} ${p.oem}`.toLowerCase().includes(query.toLowerCase())),[initialListings,query,category]);
 return <><Header/><main>
  <section className="dot-grid overflow-hidden bg-[#173c31] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div className="animate-in"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/8 px-3 py-1.5 text-xs font-bold text-[#d4f44d]"><Sparkles size={14}/>Smarter parts search for UK drivers</div><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">The right part.<br/><span className="text-[#d4f44d]">First time.</span></h1><p className="mt-6 max-w-xl text-lg leading-7 text-white/72">Search verified automotive parts by vehicle, gearbox code or OEM number — supplied by trusted UK garages.</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-white/75"><span className="flex items-center gap-2"><BadgeCheck size={18} className="text-[#d4f44d]"/>Verified garages</span><span className="flex items-center gap-2"><ShieldCheck size={18} className="text-[#d4f44d]"/>Fitment confidence</span><span className="flex items-center gap-2"><Truck size={18} className="text-[#d4f44d]"/>UK-wide delivery</span></div></div>
  <div className="animate-in rounded-[28px] bg-[#f5f2ea] p-5 text-[#12221d] shadow-2xl [animation-delay:120ms] sm:p-7"><p className="text-sm font-bold">1. Tell us about your vehicle</p><button onClick={()=>setVehicle(vehicle.includes("Volkswagen")?"Audi A3 · 2018 · 2.0 TDI":"Volkswagen Golf · 2017 · 2.0 TDI")} className="mt-3 flex w-full items-center justify-between rounded-xl border border-black/12 bg-white p-4 text-left font-semibold"><span>{vehicle}</span><ChevronDown size={18}/></button><div className="my-5 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.15em] text-[#78827d]"><span className="h-px flex-1 bg-black/10"/>then<span className="h-px flex-1 bg-black/10"/></div><label className="text-sm font-bold" htmlFor="hero-search">2. What part do you need?</label><div className="mt-3 flex rounded-xl border border-black/12 bg-white p-1.5 focus-within:ring-2 focus-within:ring-[#173c31]"><Search className="ml-3 mt-3 text-[#63706a]" size={19}/><input id="hero-search" value={query} onChange={(e)=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent px-3 outline-none" placeholder="Part name, OEM or gearbox code"/><a href="#marketplace" className="rounded-lg bg-[#d4f44d] px-5 py-3 text-sm font-black">Search</a></div><p className="mt-3 text-xs text-[#63706a]">Try: <button onClick={()=>setQuery("02E")} className="font-semibold underline">02E</button>, <button onClick={()=>setQuery("DQ200")} className="font-semibold underline">DQ200 mechatronic</button>, <button onClick={()=>setQuery("0BH")} className="font-semibold underline">0BH valve body</button></p></div></div></section>
  <section id="marketplace" className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-black uppercase tracking-[.2em] text-[#287154]">Marketplace</p><h2 className="text-3xl font-black tracking-[-.04em] sm:text-4xl">Parts matched with confidence</h2><p className="mt-2 text-[#63706a]">{filtered.length} verified listings ready to dispatch</p></div><button className="flex w-fit items-center gap-2 rounded-full border border-black/15 bg-white px-4 py-2.5 text-sm font-bold"><SlidersHorizontal size={17}/>All filters</button></div><div className="mb-8 flex gap-2 overflow-x-auto pb-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${category===c?"bg-[#173c31] text-white":"border border-black/10 bg-white"}`}>{c}</button>)}</div>{filtered.length?<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(item=><ProductCard key={item.id} item={item} saved={saved.includes(item.id)} onSave={()=>setSaved(s=>s.includes(item.id)?s.filter(id=>id!==item.id):[...s,item.id])}/>)}</div>:<div className="rounded-3xl border border-dashed border-black/20 bg-white py-20 text-center"><Search className="mx-auto mb-4 text-[#63706a]"/><h3 className="text-xl font-bold">No exact matches yet</h3><p className="mt-2 text-[#63706a]">Try a gearbox family, OEM number or a broader category.</p><button onClick={()=>{setQuery("");setCategory("All parts")}} className="mt-5 font-bold underline">Clear search</button></div>}</section>
  <section className="bg-[#f0eee6]"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-3">{[["01 · IDENTIFY","Start with the vehicle","Make, model, generation, engine and gearbox narrow the catalogue before you buy."],["02 · VERIFY","Check every identifier","OEM and gearbox codes sit beside plain-language fitment notes, not hidden in descriptions."],["03 · BUY","Choose a trusted garage","Compare condition, dispatch time, stock and seller reputation in one place."]].map(([n,t,d])=><div key={n}><span className="font-mono text-xs font-bold text-[#287154]">{n}</span><h3 className="mt-3 text-xl font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-[#63706a]">{d}</p></div>)}</div></section>
  <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="flex flex-col items-start justify-between gap-6 rounded-[28px] bg-[#d4f44d] p-8 sm:flex-row sm:items-center sm:p-12"><div><p className="text-xs font-black uppercase tracking-[.2em]">For garages & specialists</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Turn shelf stock into sales.</h2><p className="mt-2 max-w-xl text-[#31413a]">List parts, add compatibility and manage enquiries from one focused workspace.</p></div><a href="/sell" className="flex items-center gap-2 rounded-full bg-[#173c31] px-6 py-3.5 font-bold text-white">Start selling <ArrowRight size={18}/></a></div></section>
 </main><footer className="border-t border-black/10 px-4 py-8 text-sm text-[#63706a]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 sm:flex-row"><span>© 2026 SecondPart Ltd.</span><span>Built for the UK automotive trade.</span></div></footer></>;
}
