"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireSeller } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getSellerForOwner } from "@/lib/data/marketplace";
import type { ActionState,ListingStatus,PartCondition } from "@/lib/types";

const slugify=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);
const readListing=(formData:FormData)=>{const price=Number(formData.get("price"));const stock=Number(formData.get("stock"));const dispatchDays=Number(formData.get("dispatchDays"));const condition=String(formData.get("condition")) as PartCondition;const status=String(formData.get("status")) as ListingStatus;return {title:String(formData.get("title")??"").trim(),description:String(formData.get("description")??"").trim(),category_id:String(formData.get("categoryId")??""),condition,price_pence:Math.round(price*100),stock,manufacturer:String(formData.get("manufacturer")??"").trim()||null,part_number:String(formData.get("partNumber")??"").trim()||null,oem_number:String(formData.get("oemNumber")??"").trim()||null,gearbox_family:String(formData.get("gearboxFamily")??"").trim()||null,gearbox_code:String(formData.get("gearboxCode")??"").trim()||null,dispatch_days:dispatchDays,status};};
function validateListing(value:ReturnType<typeof readListing>):string|null{if(value.title.length<5)return "Title must contain at least 5 characters.";if(value.description.length<20)return "Description must contain at least 20 characters.";if(!value.category_id)return "Choose a category.";if(!(["new","reconditioned","used"] as string[]).includes(value.condition))return "Choose a valid condition.";if(!(["draft","active"] as string[]).includes(value.status))return "Choose draft or active.";if(!Number.isInteger(value.price_pence)||value.price_pence<0)return "Enter a valid price.";if(!Number.isInteger(value.stock)||value.stock<0)return "Enter a valid stock quantity.";return null;}
async function normalizeForCategory(value:ReturnType<typeof readListing>){const supabase=await createSupabaseServerClient();const {data,error}=await supabase.from("categories").select("is_transmission_related").eq("id",value.category_id).maybeSingle();if(error||!data)return {value:null,error:error?.message??"Choose a valid category."};if(data.is_transmission_related&&(!value.gearbox_family||!value.gearbox_code))return {value:null,error:"Gearbox family and code are required for this transmission-related category."};return {value:data.is_transmission_related?value:{...value,gearbox_family:null,gearbox_code:null},error:null};}
async function uploadImage(partId:string,userId:string,title:string,file:File){if(!file.size)return null;if(file.size>5*1024*1024)throw new Error("Image must be 5 MB or smaller.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Use a JPG, PNG or WebP image.");const extension=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${userId}/${partId}/${crypto.randomUUID()}.${extension}`;const supabase=await createSupabaseServerClient();const {error:uploadError}=await supabase.storage.from("part-images").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {error:recordError}=await supabase.from("part_images").insert({part_id:partId,storage_path:path,alt_text:title,position:0});if(recordError){await supabase.storage.from("part-images").remove([path]);throw recordError;}return path;}
async function replaceFitments(partId:string,vehicleIds:string[]){const supabase=await createSupabaseServerClient();const {error:deleteError}=await supabase.from("part_fitments").delete().eq("part_id",partId);if(deleteError)throw deleteError;if(vehicleIds.length){const {error}=await supabase.from("part_fitments").insert(vehicleIds.map(vehicle_id=>({part_id:partId,vehicle_id})));if(error)throw error;}}

export async function createSellerProfile(_previous:ActionState,formData:FormData):Promise<ActionState>{const {user}=await requireSeller("/dashboard");const businessName=String(formData.get("businessName")??"").trim();const location=String(formData.get("location")??"").trim();const postcode=String(formData.get("postcode")??"").trim();const description=String(formData.get("description")??"").trim();if(businessName.length<2||!location||description.length<20)return {status:"error",message:"Complete the business name, location and a description of at least 20 characters."};const supabase=await createSupabaseServerClient();const {error}=await supabase.from("sellers").insert({owner_id:user.id,business_name:businessName,slug:`${slugify(businessName)}-${user.id.slice(0,6)}`,location,postcode:postcode||null,description});if(error)return {status:"error",message:error.message};revalidatePath("/dashboard");redirect("/dashboard");}
export async function createListing(_previous:ActionState,formData:FormData):Promise<ActionState>{const {user}=await requireSeller("/dashboard/listings/new");const seller=await getSellerForOwner(user.id);if(!seller)return {status:"error",message:"Create your seller profile first."};const raw=readListing(formData);const invalid=validateListing(raw);if(invalid)return {status:"error",message:invalid};const normalized=await normalizeForCategory(raw);if(normalized.error||!normalized.value)return {status:"error",message:normalized.error??"Listing could not be validated."};const value=normalized.value;const supabase=await createSupabaseServerClient();const {data,error}=await supabase.from("parts").insert({...value,seller_id:seller.id,slug:`${slugify(value.title)}-${crypto.randomUUID().slice(0,8)}`}).select("id,slug").single();if(error)return {status:"error",message:error.message};try{await replaceFitments(data.id,formData.getAll("vehicleIds").map(String));const file=formData.get("image");if(file instanceof File)await uploadImage(data.id,user.id,value.title,file);}catch(error){return {status:"error",message:error instanceof Error?error.message:"The listing was created, but related data could not be saved."};}revalidatePath("/");revalidatePath("/dashboard");redirect("/dashboard?created=1");}
export async function updateListing(_previous:ActionState,formData:FormData):Promise<ActionState>{const {user}=await requireSeller("/dashboard");const seller=await getSellerForOwner(user.id);if(!seller)return {status:"error",message:"Seller profile not found."};const partId=String(formData.get("partId")??"");const raw=readListing(formData);const invalid=validateListing(raw);if(invalid)return {status:"error",message:invalid};const normalized=await normalizeForCategory(raw);if(normalized.error||!normalized.value)return {status:"error",message:normalized.error??"Listing could not be validated."};const value=normalized.value;const supabase=await createSupabaseServerClient();const {data,error}=await supabase.from("parts").update(value).eq("id",partId).eq("seller_id",seller.id).select("id,slug").single();if(error||!data)return {status:"error",message:error?.message??"Listing not found."};try{await replaceFitments(partId,formData.getAll("vehicleIds").map(String));const file=formData.get("image");if(file instanceof File)await uploadImage(partId,user.id,value.title,file);}catch(error){return {status:"error",message:error instanceof Error?error.message:"Listing saved, but related data could not be updated."};}revalidatePath("/");revalidatePath(`/parts/${data.slug}`);revalidatePath("/dashboard");redirect("/dashboard?updated=1");}
export async function archiveListing(formData:FormData){const {user}=await requireSeller("/dashboard");const seller=await getSellerForOwner(user.id);if(!seller)return;const partId=String(formData.get("partId")??"");const supabase=await createSupabaseServerClient();await supabase.from("parts").update({status:"archived"}).eq("id",partId).eq("seller_id",seller.id);revalidatePath("/");revalidatePath("/dashboard");}
export async function updateStock(formData:FormData){const {user}=await requireSeller("/dashboard");const seller=await getSellerForOwner(user.id);if(!seller)return;const partId=String(formData.get("partId")??"");const stock=Math.max(0,Math.floor(Number(formData.get("stock"))));const supabase=await createSupabaseServerClient();await supabase.from("parts").update({stock}).eq("id",partId).eq("seller_id",seller.id);revalidatePath("/");revalidatePath("/dashboard");}
